{
 "title": "MyBMW Exported data",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Car Fuel Cost Delta 💶",
   "type": "stat",
   "description": "Car fuel cost in EUR",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(delta(currentMileages {job=\"bmw_exporter\"}[$__range])/17.2)*1.80",
     "legendFormat": "€ EUR"
    }
   ]
  },
  {
   "title": "Estimated Fuel Refil Cost ⛽",
   "type": "stat",
   "description": "Estimated fuel refil cost based on last available remaining liters",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((combustionFuelLevel_remainingFuelLiters{job=\"bmw_exporter\"}-52)*-1)*(gas_fuel_price{job=\"bmw_exporter\"})",
     "legendFormat": "€ EUR"
    }
   ]
  },
  {
   "title": "Current Gas Fuel Cost /L⛽",
   "type": "stat",
   "description": "Gas cost based with external - Tamoil median cost",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gas_fuel_price{job=\"bmw_exporter\"}",
     "legendFormat": "€ EUR"
    }
   ]
  },
  {
   "title": "Autonomy range",
   "type": "timeseries",
   "description": "Car autonomy range in kilometers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "range{job=\"bmw_exporter\"} ",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "sum(predict_linear(range {job=\"bmw_exporter\"}[4d],48*3600))",
     "legendFormat": "Predicted  Linear range"
    }
   ]
  },
  {
   "title": "Car Mileage",
   "type": "timeseries",
   "description": "Car mileage in kilometers",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "currentMileages{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "sum(predict_linear(currentMileages  {job=\"bmw_exporter\"}[4d],48*3600))",
     "legendFormat": "Predicted Linerar Current Mileages"
    }
   ]
  },
  {
   "title": "Fuel Available",
   "type": "timeseries",
   "description": "Car autonomy range in kilometers",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "combustionFuelLevel_remainingFuelLiters{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Check Control Message Severity",
   "type": "state-timeline",
   "description": "Value 5 means = LOW\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "checkControlMessages_severity{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Car Status codes",
   "type": "state-timeline",
   "description": "Car status codes",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "checkControlMessages_severity{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "checkControlMessages_type{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "doorsState_combinedSecurityState{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "doorsState_combinedState{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "hood{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "leftFront{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "leftRear{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "rightRear{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "rightFront{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "trunk{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "windowsStatecombinedState{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "windowsStateleftFront{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "windowsStateleftRear{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "windowsStaterightFront{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "windowsStaterightRear{job=\"bmw_exporter\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Position",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "{job=\"bmw_exporter\",  label=\"geo\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}